version: '3.9'

services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.20-alpine
    volumes:
      - ./:/var/www/html
      - .docker/nginx/rootfs/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      target: base
    volumes:
      - ./:/var/www/html
